# Generated by Django 4.1.1 on 2022-10-05 15:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=200, unique=True)),
                ('category_slug', models.SlugField(default='iyas', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(default='/static/assets/images/profile.jpg', upload_to='profile_img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallpapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='wallpapers')),
                ('download_count', models.IntegerField(default=0)),
                ('wallpappers_count', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='uploadapp.category')),
                ('profile_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uploadapp.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Downloaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_count', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadapp.wallpapers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
