# Generated by Django 4.1.1 on 2022-10-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpapers',
            name='profile_user',
        ),
    ]
