# Generated by Django 4.1.1 on 2022-10-06 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_remove_wallpapers_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaded',
            name='downloaded_count',
        ),
        migrations.AddField(
            model_name='downloaded',
            name='count_of_downloads',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wallpapers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.CreateModel(
            name='Downloadcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_image_downloads', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadapp.wallpapers')),
            ],
        ),
    ]
